stages:
  - deploy

deploy_backend:
  stage: deploy
  only:
    - Yi
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H gitlab.liu.se >> ~/.ssh/known_hosts
    - ssh-keyscan -H YOUR_EC2_PUBLIC_IP >> ~/.ssh/known_hosts
  script:
    - ssh ec2-user@YOUR_EC2_PUBLIC_IP << 'EOF'
        cd ~/web/backend
        git pull origin Yi
        yarn install
        yarn build
        pkill -f "ts-node" || true
        nohup npm run dev > backend.log 2>&1 &
      EOF
