<template>
  <div class="max-w-2xl mx-auto p-4">
    <el-button type="warning" :loading="loading" @click="submitMultipleArticles">
      Generate 100 Articles
    </el-button>
    <el-card>
      <template #header>Create New Article</template>

      <el-form :model="form" :rules="rules" ref="formRef" label-width="80px" status-icon>
        <el-form-item label="Title" prop="title">
          <el-input v-model="form.title" placeholder="Enter article title" />
        </el-form-item>

        <el-form-item label="Category" prop="category">
          <el-input v-model="form.category" placeholder="Enter category tag" />
        </el-form-item>

        <el-form-item label="Content" prop="content">
          <el-input
            v-model="form.content"
            type="textarea"
            :rows="8"
            placeholder="Enter article content"
          />
        </el-form-item>

        <el-form-item>
          <el-button type="primary" :loading="loading" @click="submitForm">Submit</el-button>
          <el-button @click="resetForm">Reset</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElForm, ElMessage } from 'element-plus'
import { API_CreateArticle } from '@/api'
import type { CreateArticleBody } from '../../../backend/src/types/request'

const router = useRouter()

const form = ref<CreateArticleBody>({
  title: '',
  category: '',
  content: '',
})

const rules = {
  title: [{ required: true, message: 'Title is required', trigger: 'blur' }],
  category: [{ required: true, message: 'Category is required', trigger: 'blur' }],
  content: [{ required: true, message: 'Content is required', trigger: 'blur' }],
}

const formRef = ref<InstanceType<typeof ElForm>>()
const loading = ref(false)

const submitForm = async () => {
  if (!formRef.value) return

  await formRef.value.validate(async (valid) => {
    if (valid) {
      loading.value = true
      try {
        const res = await API_CreateArticle(form.value)
        if (res.success) {
          ElMessage.success('Article created successfully!')
          router.push('/') // Redirect to homepage
        } else {
          ElMessage.error(res.error || 'Article creation failed')
        }
      } catch (err) {
        ElMessage.error('Request failed. Please try again.')
      } finally {
        loading.value = false
      }
    }
  })
}

const resetForm = () => {
  form.value = {
    title: '',
    category: '',
    content: '',
  }
}

const submitMultipleArticles = async () => {
  loading.value = true
  const titles = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Epsilon']
  const contents = [
    'Lorem ipsum dolor sit amet.',
    'Sample content goes here.',
    'Test article body text.',
    'Generated by AI for testing.',
    'Random description content.',
  ]

  for (let i = 0; i < 100; i++) {
    const article = {
      title: `${titles[i % titles.length]} Article #${i + 1}`,
      category: `Category${(i % 5) + 1}`,
      content: contents[i % contents.length],
    }

    try {
      const res = await API_CreateArticle(article)
      if (!res.success) {
        console.warn(`Failed to create article ${i + 1}: ${res.error}`)
      }
    } catch (err) {
      console.error(`Error creating article ${i + 1}`, err)
    }
  }

  ElMessage.success('Finished creating 100 test articles!')
  loading.value = false
  router.push('/')
}
</script>
